version: "3.0"
services:
    wordpress:
        image: wordpress
        restart: unless-stopped
        enviroment:
            WORDPRESS_DB_HOST: db
            WORDPRESS_DB_NAME: wordpress
            WORDPRESS_DB_USER: wordpress
            WORDPRESS_DB_PASSWORD: Aigh5Oir

    db:
        image: mariadb
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: ebeeph2Y
            MYSQL_DATABASE: wordpress
            MYSQL_USER: wordpress
            MYSQL_PASSWORD: Aigh5Oir